/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertId = IDL.Nat;
export const AlertType = IDL.Variant({
  'BudgetOverrun' : IDL.Null,
  'PendingInvoice' : IDL.Null,
  'LowInventory' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const ProjectId = IDL.Nat;
export const AlertSeverity = IDL.Variant({
  'Info' : IDL.Null,
  'Critical' : IDL.Null,
  'Warning' : IDL.Null,
});
export const AlertPublic = IDL.Record({
  'id' : AlertId,
  'alertType' : AlertType,
  'acknowledgedAt' : IDL.Opt(Timestamp),
  'acknowledgedBy' : IDL.Opt(UserId),
  'createdAt' : Timestamp,
  'isAcknowledged' : IDL.Bool,
  'relatedEntityId' : IDL.Nat,
  'projectId' : ProjectId,
  'message' : IDL.Text,
  'severity' : AlertSeverity,
});
export const BudgetCategory = IDL.Variant({
  'Labor' : IDL.Null,
  'Overhead' : IDL.Null,
  'Materials' : IDL.Null,
  'Other' : IDL.Null,
  'Equipment' : IDL.Null,
});
export const CreateBudgetPayload = IDL.Record({
  'projectId' : ProjectId,
  'notes' : IDL.Opt(IDL.Text),
  'allocatedAmount' : IDL.Float64,
  'category' : BudgetCategory,
});
export const BudgetId = IDL.Nat;
export const BudgetPublic = IDL.Record({
  'id' : BudgetId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'projectId' : ProjectId,
  'notes' : IDL.Opt(IDL.Text),
  'allocatedAmount' : IDL.Float64,
  'category' : BudgetCategory,
  'spentAmount' : IDL.Float64,
});
export const SupplierId = IDL.Nat;
export const CreateDeliveryPayload = IDL.Record({
  'projectId' : ProjectId,
  'notes' : IDL.Opt(IDL.Text),
  'expectedDate' : Timestamp,
  'supplierId' : SupplierId,
});
export const DeliveryStatus = IDL.Variant({
  'InTransit' : IDL.Null,
  'Delivered' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const DeliveryPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : DeliveryStatus,
  'createdAt' : Timestamp,
  'actualDate' : IDL.Opt(Timestamp),
  'updatedAt' : Timestamp,
  'projectId' : ProjectId,
  'notes' : IDL.Opt(IDL.Text),
  'expectedDate' : Timestamp,
  'supplierId' : SupplierId,
});
export const MaterialId = IDL.Nat;
export const InvoiceLineItem = IDL.Record({
  'totalCost' : IDL.Float64,
  'description' : IDL.Text,
  'materialId' : IDL.Opt(MaterialId),
  'quantity' : IDL.Float64,
  'unitCost' : IDL.Float64,
});
export const CreateInvoicePayload = IDL.Record({
  'lineItems' : IDL.Vec(InvoiceLineItem),
  'dueDate' : IDL.Opt(Timestamp),
  'projectId' : ProjectId,
  'notes' : IDL.Opt(IDL.Text),
  'supplierId' : IDL.Opt(SupplierId),
});
export const InvoiceId = IDL.Nat;
export const InvoiceStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Draft' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const InvoiceType = IDL.Variant({
  'SupplierDelivery' : IDL.Null,
  'Manual' : IDL.Null,
});
export const InvoicePublic = IDL.Record({
  'id' : InvoiceId,
  'status' : InvoiceStatus,
  'lineItems' : IDL.Vec(InvoiceLineItem),
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'dueDate' : IDL.Opt(Timestamp),
  'updatedAt' : Timestamp,
  'invoiceType' : InvoiceType,
  'projectId' : ProjectId,
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'paidAt' : IDL.Opt(Timestamp),
  'supplierId' : IDL.Opt(SupplierId),
});
export const MaterialCategory = IDL.Variant({
  'Steel' : IDL.Null,
  'Plumbing' : IDL.Null,
  'Sand' : IDL.Null,
  'Cement' : IDL.Null,
  'Wood' : IDL.Null,
  'Bricks' : IDL.Null,
  'Aggregate' : IDL.Null,
  'Paint' : IDL.Null,
  'Electrical' : IDL.Null,
  'Other' : IDL.Null,
});
export const CreateMaterialPayload = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'projectId' : ProjectId,
  'category' : MaterialCategory,
  'reorderThreshold' : IDL.Float64,
});
export const MaterialPublic = IDL.Record({
  'id' : MaterialId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'updatedAt' : Timestamp,
  'projectId' : ProjectId,
  'category' : MaterialCategory,
  'currentStock' : IDL.Float64,
  'reorderThreshold' : IDL.Float64,
});
export const CreatePhasePayload = IDL.Record({
  'endDate' : IDL.Opt(Timestamp),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'budgetAllocation' : IDL.Float64,
  'projectId' : ProjectId,
  'startDate' : IDL.Opt(Timestamp),
});
export const PhaseId = IDL.Nat;
export const PhaseStatus = IDL.Variant({
  'Planned' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const PhasePublic = IDL.Record({
  'id' : PhaseId,
  'status' : PhaseStatus,
  'endDate' : IDL.Opt(Timestamp),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'budgetAllocation' : IDL.Float64,
  'projectId' : ProjectId,
  'startDate' : IDL.Opt(Timestamp),
});
export const CreateProjectPayload = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'siteLocation' : IDL.Text,
  'totalBudget' : IDL.Float64,
});
export const ProjectStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'Completed' : IDL.Null,
});
export const ProjectPublic = IDL.Record({
  'id' : ProjectId,
  'status' : ProjectStatus,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'siteLocation' : IDL.Text,
  'updatedAt' : Timestamp,
  'totalBudget' : IDL.Float64,
});
export const CreateSupplierPayload = IDL.Record({
  'materialCategories' : IDL.Vec(MaterialCategory),
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const SupplierPublic = IDL.Record({
  'id' : SupplierId,
  'materialCategories' : IDL.Vec(MaterialCategory),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'contactPerson' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'updatedAt' : Timestamp,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const CategoryVariance = IDL.Record({
  'allocated' : IDL.Float64,
  'variance' : IDL.Float64,
  'spent' : IDL.Float64,
  'category' : BudgetCategory,
});
export const BudgetVariance = IDL.Record({
  'totalAllocated' : IDL.Float64,
  'projectName' : IDL.Text,
  'categoryBreakdown' : IDL.Vec(CategoryVariance),
  'variancePercent' : IDL.Float64,
  'variance' : IDL.Float64,
  'totalSpent' : IDL.Float64,
  'projectId' : ProjectId,
  'isOverrun' : IDL.Bool,
});
export const InventoryBalance = IDL.Record({
  'isBelowThreshold' : IDL.Bool,
  'unit' : IDL.Text,
  'materialId' : MaterialId,
  'projectId' : ProjectId,
  'category' : MaterialCategory,
  'currentStock' : IDL.Float64,
  'materialName' : IDL.Text,
  'reorderThreshold' : IDL.Float64,
});
export const TransactionId = IDL.Nat;
export const TransactionType = IDL.Variant({
  'Outflow' : IDL.Null,
  'Inflow' : IDL.Null,
});
export const InventoryTransaction = IDL.Record({
  'id' : TransactionId,
  'transactionDate' : Timestamp,
  'transactionType' : TransactionType,
  'createdAt' : Timestamp,
  'invoiceId' : IDL.Opt(InvoiceId),
  'totalCost' : IDL.Float64,
  'materialId' : MaterialId,
  'recordedBy' : UserId,
  'projectId' : ProjectId,
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Float64,
  'supplierId' : IDL.Opt(SupplierId),
  'phaseId' : IDL.Opt(PhaseId),
  'unitCost' : IDL.Float64,
  'qrCode' : IDL.Opt(IDL.Text),
});
export const Role = IDL.Variant({
  'ProjectManager' : IDL.Null,
  'Admin' : IDL.Null,
  'SiteEngineer' : IDL.Null,
  'FinanceProcurement' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const PhaseSpending = IDL.Record({
  'totalSpent' : IDL.Float64,
  'phaseName' : IDL.Text,
  'phaseId' : PhaseId,
});
export const MaterialSpending = IDL.Record({
  'totalCost' : IDL.Float64,
  'materialId' : MaterialId,
  'materialName' : IDL.Text,
  'totalQuantity' : IDL.Float64,
});
export const SpendingReport = IDL.Record({
  'phaseBreakdown' : IDL.Vec(PhaseSpending),
  'projectName' : IDL.Text,
  'materialBreakdown' : IDL.Vec(MaterialSpending),
  'reportGeneratedAt' : Timestamp,
  'totalSpent' : IDL.Float64,
  'projectId' : ProjectId,
});
export const LogInflowPayload = IDL.Record({
  'transactionDate' : Timestamp,
  'materialId' : MaterialId,
  'projectId' : ProjectId,
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Float64,
  'supplierId' : IDL.Opt(SupplierId),
  'phaseId' : IDL.Opt(PhaseId),
  'unitCost' : IDL.Float64,
  'qrCode' : IDL.Opt(IDL.Text),
});
export const LogOutflowPayload = IDL.Record({
  'transactionDate' : Timestamp,
  'materialId' : MaterialId,
  'projectId' : ProjectId,
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Float64,
  'phaseId' : IDL.Opt(PhaseId),
  'unitCost' : IDL.Float64,
  'qrCode' : IDL.Opt(IDL.Text),
});
export const RegisterUserPayload = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
});
export const UpdateBudgetPayload = IDL.Record({
  'notes' : IDL.Opt(IDL.Text),
  'allocatedAmount' : IDL.Opt(IDL.Float64),
});
export const UpdateInvoiceStatusPayload = IDL.Record({
  'status' : InvoiceStatus,
  'invoiceId' : InvoiceId,
});
export const UpdateProjectPayload = IDL.Record({
  'status' : IDL.Opt(ProjectStatus),
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'siteLocation' : IDL.Opt(IDL.Text),
  'totalBudget' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  'acknowledgeAlert' : IDL.Func([AlertId], [AlertPublic], []),
  'createBudget' : IDL.Func([CreateBudgetPayload], [BudgetPublic], []),
  'createDelivery' : IDL.Func([CreateDeliveryPayload], [DeliveryPublic], []),
  'createInvoice' : IDL.Func([CreateInvoicePayload], [InvoicePublic], []),
  'createMaterial' : IDL.Func([CreateMaterialPayload], [MaterialPublic], []),
  'createPhase' : IDL.Func([CreatePhasePayload], [PhasePublic], []),
  'createProject' : IDL.Func([CreateProjectPayload], [ProjectPublic], []),
  'createSupplier' : IDL.Func([CreateSupplierPayload], [SupplierPublic], []),
  'getBudgetVariance' : IDL.Func([ProjectId], [BudgetVariance], ['query']),
  'getBudgetsByProject' : IDL.Func(
      [ProjectId],
      [IDL.Vec(BudgetPublic)],
      ['query'],
    ),
  'getInventoryBalance' : IDL.Func(
      [ProjectId],
      [IDL.Vec(InventoryBalance)],
      ['query'],
    ),
  'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(InvoicePublic)], ['query']),
  'getMaterialByQrCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(InventoryTransaction)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
  'getPendingInvoices' : IDL.Func(
      [IDL.Opt(ProjectId)],
      [IDL.Vec(InvoicePublic)],
      ['query'],
    ),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(ProjectPublic)], ['query']),
  'getSpendingReport' : IDL.Func([ProjectId], [SpendingReport], ['query']),
  'getSupplier' : IDL.Func([SupplierId], [IDL.Opt(SupplierPublic)], ['query']),
  'isUserRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'listAlerts' : IDL.Func(
      [IDL.Opt(ProjectId), IDL.Bool],
      [IDL.Vec(AlertPublic)],
      ['query'],
    ),
  'listDeliveries' : IDL.Func(
      [IDL.Opt(SupplierId), IDL.Opt(ProjectId), IDL.Opt(DeliveryStatus)],
      [IDL.Vec(DeliveryPublic)],
      ['query'],
    ),
  'listInventoryTransactions' : IDL.Func(
      [IDL.Opt(ProjectId), IDL.Opt(MaterialId), IDL.Opt(TransactionType)],
      [IDL.Vec(InventoryTransaction)],
      ['query'],
    ),
  'listInvoices' : IDL.Func(
      [IDL.Opt(ProjectId), IDL.Opt(SupplierId), IDL.Opt(InvoiceStatus)],
      [IDL.Vec(InvoicePublic)],
      ['query'],
    ),
  'listMaterials' : IDL.Func(
      [IDL.Opt(ProjectId)],
      [IDL.Vec(MaterialPublic)],
      ['query'],
    ),
  'listPhasesByProject' : IDL.Func(
      [ProjectId],
      [IDL.Vec(PhasePublic)],
      ['query'],
    ),
  'listProjects' : IDL.Func(
      [IDL.Opt(ProjectStatus)],
      [IDL.Vec(ProjectPublic)],
      ['query'],
    ),
  'listSuppliers' : IDL.Func([], [IDL.Vec(SupplierPublic)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
  'logMaterialInflow' : IDL.Func(
      [LogInflowPayload],
      [InventoryTransaction],
      [],
    ),
  'logMaterialOutflow' : IDL.Func(
      [LogOutflowPayload],
      [InventoryTransaction],
      [],
    ),
  'registerUser' : IDL.Func([RegisterUserPayload], [UserPublic], []),
  'runAlertChecks' : IDL.Func([], [IDL.Nat], []),
  'updateBudget' : IDL.Func(
      [BudgetId, UpdateBudgetPayload],
      [BudgetPublic],
      [],
    ),
  'updateDeliveryStatus' : IDL.Func(
      [IDL.Nat, DeliveryStatus, IDL.Opt(Timestamp)],
      [DeliveryPublic],
      [],
    ),
  'updateInvoiceStatus' : IDL.Func(
      [UpdateInvoiceStatusPayload],
      [InvoicePublic],
      [],
    ),
  'updateProject' : IDL.Func(
      [ProjectId, UpdateProjectPayload],
      [ProjectPublic],
      [],
    ),
  'updateUserRole' : IDL.Func([UserId, Role], [UserPublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertId = IDL.Nat;
  const AlertType = IDL.Variant({
    'BudgetOverrun' : IDL.Null,
    'PendingInvoice' : IDL.Null,
    'LowInventory' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const ProjectId = IDL.Nat;
  const AlertSeverity = IDL.Variant({
    'Info' : IDL.Null,
    'Critical' : IDL.Null,
    'Warning' : IDL.Null,
  });
  const AlertPublic = IDL.Record({
    'id' : AlertId,
    'alertType' : AlertType,
    'acknowledgedAt' : IDL.Opt(Timestamp),
    'acknowledgedBy' : IDL.Opt(UserId),
    'createdAt' : Timestamp,
    'isAcknowledged' : IDL.Bool,
    'relatedEntityId' : IDL.Nat,
    'projectId' : ProjectId,
    'message' : IDL.Text,
    'severity' : AlertSeverity,
  });
  const BudgetCategory = IDL.Variant({
    'Labor' : IDL.Null,
    'Overhead' : IDL.Null,
    'Materials' : IDL.Null,
    'Other' : IDL.Null,
    'Equipment' : IDL.Null,
  });
  const CreateBudgetPayload = IDL.Record({
    'projectId' : ProjectId,
    'notes' : IDL.Opt(IDL.Text),
    'allocatedAmount' : IDL.Float64,
    'category' : BudgetCategory,
  });
  const BudgetId = IDL.Nat;
  const BudgetPublic = IDL.Record({
    'id' : BudgetId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'projectId' : ProjectId,
    'notes' : IDL.Opt(IDL.Text),
    'allocatedAmount' : IDL.Float64,
    'category' : BudgetCategory,
    'spentAmount' : IDL.Float64,
  });
  const SupplierId = IDL.Nat;
  const CreateDeliveryPayload = IDL.Record({
    'projectId' : ProjectId,
    'notes' : IDL.Opt(IDL.Text),
    'expectedDate' : Timestamp,
    'supplierId' : SupplierId,
  });
  const DeliveryStatus = IDL.Variant({
    'InTransit' : IDL.Null,
    'Delivered' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const DeliveryPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : DeliveryStatus,
    'createdAt' : Timestamp,
    'actualDate' : IDL.Opt(Timestamp),
    'updatedAt' : Timestamp,
    'projectId' : ProjectId,
    'notes' : IDL.Opt(IDL.Text),
    'expectedDate' : Timestamp,
    'supplierId' : SupplierId,
  });
  const MaterialId = IDL.Nat;
  const InvoiceLineItem = IDL.Record({
    'totalCost' : IDL.Float64,
    'description' : IDL.Text,
    'materialId' : IDL.Opt(MaterialId),
    'quantity' : IDL.Float64,
    'unitCost' : IDL.Float64,
  });
  const CreateInvoicePayload = IDL.Record({
    'lineItems' : IDL.Vec(InvoiceLineItem),
    'dueDate' : IDL.Opt(Timestamp),
    'projectId' : ProjectId,
    'notes' : IDL.Opt(IDL.Text),
    'supplierId' : IDL.Opt(SupplierId),
  });
  const InvoiceId = IDL.Nat;
  const InvoiceStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Draft' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const InvoiceType = IDL.Variant({
    'SupplierDelivery' : IDL.Null,
    'Manual' : IDL.Null,
  });
  const InvoicePublic = IDL.Record({
    'id' : InvoiceId,
    'status' : InvoiceStatus,
    'lineItems' : IDL.Vec(InvoiceLineItem),
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'dueDate' : IDL.Opt(Timestamp),
    'updatedAt' : Timestamp,
    'invoiceType' : InvoiceType,
    'projectId' : ProjectId,
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'paidAt' : IDL.Opt(Timestamp),
    'supplierId' : IDL.Opt(SupplierId),
  });
  const MaterialCategory = IDL.Variant({
    'Steel' : IDL.Null,
    'Plumbing' : IDL.Null,
    'Sand' : IDL.Null,
    'Cement' : IDL.Null,
    'Wood' : IDL.Null,
    'Bricks' : IDL.Null,
    'Aggregate' : IDL.Null,
    'Paint' : IDL.Null,
    'Electrical' : IDL.Null,
    'Other' : IDL.Null,
  });
  const CreateMaterialPayload = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'projectId' : ProjectId,
    'category' : MaterialCategory,
    'reorderThreshold' : IDL.Float64,
  });
  const MaterialPublic = IDL.Record({
    'id' : MaterialId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'updatedAt' : Timestamp,
    'projectId' : ProjectId,
    'category' : MaterialCategory,
    'currentStock' : IDL.Float64,
    'reorderThreshold' : IDL.Float64,
  });
  const CreatePhasePayload = IDL.Record({
    'endDate' : IDL.Opt(Timestamp),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'budgetAllocation' : IDL.Float64,
    'projectId' : ProjectId,
    'startDate' : IDL.Opt(Timestamp),
  });
  const PhaseId = IDL.Nat;
  const PhaseStatus = IDL.Variant({
    'Planned' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const PhasePublic = IDL.Record({
    'id' : PhaseId,
    'status' : PhaseStatus,
    'endDate' : IDL.Opt(Timestamp),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'budgetAllocation' : IDL.Float64,
    'projectId' : ProjectId,
    'startDate' : IDL.Opt(Timestamp),
  });
  const CreateProjectPayload = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'siteLocation' : IDL.Text,
    'totalBudget' : IDL.Float64,
  });
  const ProjectStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const ProjectPublic = IDL.Record({
    'id' : ProjectId,
    'status' : ProjectStatus,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'siteLocation' : IDL.Text,
    'updatedAt' : Timestamp,
    'totalBudget' : IDL.Float64,
  });
  const CreateSupplierPayload = IDL.Record({
    'materialCategories' : IDL.Vec(MaterialCategory),
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SupplierPublic = IDL.Record({
    'id' : SupplierId,
    'materialCategories' : IDL.Vec(MaterialCategory),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'contactPerson' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'updatedAt' : Timestamp,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CategoryVariance = IDL.Record({
    'allocated' : IDL.Float64,
    'variance' : IDL.Float64,
    'spent' : IDL.Float64,
    'category' : BudgetCategory,
  });
  const BudgetVariance = IDL.Record({
    'totalAllocated' : IDL.Float64,
    'projectName' : IDL.Text,
    'categoryBreakdown' : IDL.Vec(CategoryVariance),
    'variancePercent' : IDL.Float64,
    'variance' : IDL.Float64,
    'totalSpent' : IDL.Float64,
    'projectId' : ProjectId,
    'isOverrun' : IDL.Bool,
  });
  const InventoryBalance = IDL.Record({
    'isBelowThreshold' : IDL.Bool,
    'unit' : IDL.Text,
    'materialId' : MaterialId,
    'projectId' : ProjectId,
    'category' : MaterialCategory,
    'currentStock' : IDL.Float64,
    'materialName' : IDL.Text,
    'reorderThreshold' : IDL.Float64,
  });
  const TransactionId = IDL.Nat;
  const TransactionType = IDL.Variant({
    'Outflow' : IDL.Null,
    'Inflow' : IDL.Null,
  });
  const InventoryTransaction = IDL.Record({
    'id' : TransactionId,
    'transactionDate' : Timestamp,
    'transactionType' : TransactionType,
    'createdAt' : Timestamp,
    'invoiceId' : IDL.Opt(InvoiceId),
    'totalCost' : IDL.Float64,
    'materialId' : MaterialId,
    'recordedBy' : UserId,
    'projectId' : ProjectId,
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Float64,
    'supplierId' : IDL.Opt(SupplierId),
    'phaseId' : IDL.Opt(PhaseId),
    'unitCost' : IDL.Float64,
    'qrCode' : IDL.Opt(IDL.Text),
  });
  const Role = IDL.Variant({
    'ProjectManager' : IDL.Null,
    'Admin' : IDL.Null,
    'SiteEngineer' : IDL.Null,
    'FinanceProcurement' : IDL.Null,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const PhaseSpending = IDL.Record({
    'totalSpent' : IDL.Float64,
    'phaseName' : IDL.Text,
    'phaseId' : PhaseId,
  });
  const MaterialSpending = IDL.Record({
    'totalCost' : IDL.Float64,
    'materialId' : MaterialId,
    'materialName' : IDL.Text,
    'totalQuantity' : IDL.Float64,
  });
  const SpendingReport = IDL.Record({
    'phaseBreakdown' : IDL.Vec(PhaseSpending),
    'projectName' : IDL.Text,
    'materialBreakdown' : IDL.Vec(MaterialSpending),
    'reportGeneratedAt' : Timestamp,
    'totalSpent' : IDL.Float64,
    'projectId' : ProjectId,
  });
  const LogInflowPayload = IDL.Record({
    'transactionDate' : Timestamp,
    'materialId' : MaterialId,
    'projectId' : ProjectId,
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Float64,
    'supplierId' : IDL.Opt(SupplierId),
    'phaseId' : IDL.Opt(PhaseId),
    'unitCost' : IDL.Float64,
    'qrCode' : IDL.Opt(IDL.Text),
  });
  const LogOutflowPayload = IDL.Record({
    'transactionDate' : Timestamp,
    'materialId' : MaterialId,
    'projectId' : ProjectId,
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Float64,
    'phaseId' : IDL.Opt(PhaseId),
    'unitCost' : IDL.Float64,
    'qrCode' : IDL.Opt(IDL.Text),
  });
  const RegisterUserPayload = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
  });
  const UpdateBudgetPayload = IDL.Record({
    'notes' : IDL.Opt(IDL.Text),
    'allocatedAmount' : IDL.Opt(IDL.Float64),
  });
  const UpdateInvoiceStatusPayload = IDL.Record({
    'status' : InvoiceStatus,
    'invoiceId' : InvoiceId,
  });
  const UpdateProjectPayload = IDL.Record({
    'status' : IDL.Opt(ProjectStatus),
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'siteLocation' : IDL.Opt(IDL.Text),
    'totalBudget' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    'acknowledgeAlert' : IDL.Func([AlertId], [AlertPublic], []),
    'createBudget' : IDL.Func([CreateBudgetPayload], [BudgetPublic], []),
    'createDelivery' : IDL.Func([CreateDeliveryPayload], [DeliveryPublic], []),
    'createInvoice' : IDL.Func([CreateInvoicePayload], [InvoicePublic], []),
    'createMaterial' : IDL.Func([CreateMaterialPayload], [MaterialPublic], []),
    'createPhase' : IDL.Func([CreatePhasePayload], [PhasePublic], []),
    'createProject' : IDL.Func([CreateProjectPayload], [ProjectPublic], []),
    'createSupplier' : IDL.Func([CreateSupplierPayload], [SupplierPublic], []),
    'getBudgetVariance' : IDL.Func([ProjectId], [BudgetVariance], ['query']),
    'getBudgetsByProject' : IDL.Func(
        [ProjectId],
        [IDL.Vec(BudgetPublic)],
        ['query'],
      ),
    'getInventoryBalance' : IDL.Func(
        [ProjectId],
        [IDL.Vec(InventoryBalance)],
        ['query'],
      ),
    'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(InvoicePublic)], ['query']),
    'getMaterialByQrCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(InventoryTransaction)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
    'getPendingInvoices' : IDL.Func(
        [IDL.Opt(ProjectId)],
        [IDL.Vec(InvoicePublic)],
        ['query'],
      ),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(ProjectPublic)], ['query']),
    'getSpendingReport' : IDL.Func([ProjectId], [SpendingReport], ['query']),
    'getSupplier' : IDL.Func(
        [SupplierId],
        [IDL.Opt(SupplierPublic)],
        ['query'],
      ),
    'isUserRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'listAlerts' : IDL.Func(
        [IDL.Opt(ProjectId), IDL.Bool],
        [IDL.Vec(AlertPublic)],
        ['query'],
      ),
    'listDeliveries' : IDL.Func(
        [IDL.Opt(SupplierId), IDL.Opt(ProjectId), IDL.Opt(DeliveryStatus)],
        [IDL.Vec(DeliveryPublic)],
        ['query'],
      ),
    'listInventoryTransactions' : IDL.Func(
        [IDL.Opt(ProjectId), IDL.Opt(MaterialId), IDL.Opt(TransactionType)],
        [IDL.Vec(InventoryTransaction)],
        ['query'],
      ),
    'listInvoices' : IDL.Func(
        [IDL.Opt(ProjectId), IDL.Opt(SupplierId), IDL.Opt(InvoiceStatus)],
        [IDL.Vec(InvoicePublic)],
        ['query'],
      ),
    'listMaterials' : IDL.Func(
        [IDL.Opt(ProjectId)],
        [IDL.Vec(MaterialPublic)],
        ['query'],
      ),
    'listPhasesByProject' : IDL.Func(
        [ProjectId],
        [IDL.Vec(PhasePublic)],
        ['query'],
      ),
    'listProjects' : IDL.Func(
        [IDL.Opt(ProjectStatus)],
        [IDL.Vec(ProjectPublic)],
        ['query'],
      ),
    'listSuppliers' : IDL.Func([], [IDL.Vec(SupplierPublic)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
    'logMaterialInflow' : IDL.Func(
        [LogInflowPayload],
        [InventoryTransaction],
        [],
      ),
    'logMaterialOutflow' : IDL.Func(
        [LogOutflowPayload],
        [InventoryTransaction],
        [],
      ),
    'registerUser' : IDL.Func([RegisterUserPayload], [UserPublic], []),
    'runAlertChecks' : IDL.Func([], [IDL.Nat], []),
    'updateBudget' : IDL.Func(
        [BudgetId, UpdateBudgetPayload],
        [BudgetPublic],
        [],
      ),
    'updateDeliveryStatus' : IDL.Func(
        [IDL.Nat, DeliveryStatus, IDL.Opt(Timestamp)],
        [DeliveryPublic],
        [],
      ),
    'updateInvoiceStatus' : IDL.Func(
        [UpdateInvoiceStatusPayload],
        [InvoicePublic],
        [],
      ),
    'updateProject' : IDL.Func(
        [ProjectId, UpdateProjectPayload],
        [ProjectPublic],
        [],
      ),
    'updateUserRole' : IDL.Func([UserId, Role], [UserPublic], []),
  });
};

export const init = ({ IDL }) => { return []; };