/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertId = bigint;
export interface AlertPublic {
  'id' : AlertId,
  'alertType' : AlertType,
  'acknowledgedAt' : [] | [Timestamp],
  'acknowledgedBy' : [] | [UserId],
  'createdAt' : Timestamp,
  'isAcknowledged' : boolean,
  'relatedEntityId' : bigint,
  'projectId' : ProjectId,
  'message' : string,
  'severity' : AlertSeverity,
}
export type AlertSeverity = { 'Info' : null } |
  { 'Critical' : null } |
  { 'Warning' : null };
export type AlertType = { 'BudgetOverrun' : null } |
  { 'PendingInvoice' : null } |
  { 'LowInventory' : null };
export type BudgetCategory = { 'Labor' : null } |
  { 'Overhead' : null } |
  { 'Materials' : null } |
  { 'Other' : null } |
  { 'Equipment' : null };
export type BudgetId = bigint;
export interface BudgetPublic {
  'id' : BudgetId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'projectId' : ProjectId,
  'notes' : [] | [string],
  'allocatedAmount' : number,
  'category' : BudgetCategory,
  'spentAmount' : number,
}
export interface BudgetVariance {
  'totalAllocated' : number,
  'projectName' : string,
  'categoryBreakdown' : Array<CategoryVariance>,
  'variancePercent' : number,
  'variance' : number,
  'totalSpent' : number,
  'projectId' : ProjectId,
  'isOverrun' : boolean,
}
export interface CategoryVariance {
  'allocated' : number,
  'variance' : number,
  'spent' : number,
  'category' : BudgetCategory,
}
export interface CreateBudgetPayload {
  'projectId' : ProjectId,
  'notes' : [] | [string],
  'allocatedAmount' : number,
  'category' : BudgetCategory,
}
export interface CreateDeliveryPayload {
  'projectId' : ProjectId,
  'notes' : [] | [string],
  'expectedDate' : Timestamp,
  'supplierId' : SupplierId,
}
export interface CreateInvoicePayload {
  'lineItems' : Array<InvoiceLineItem>,
  'dueDate' : [] | [Timestamp],
  'projectId' : ProjectId,
  'notes' : [] | [string],
  'supplierId' : [] | [SupplierId],
}
export interface CreateMaterialPayload {
  'name' : string,
  'unit' : string,
  'projectId' : ProjectId,
  'category' : MaterialCategory,
  'reorderThreshold' : number,
}
export interface CreatePhasePayload {
  'endDate' : [] | [Timestamp],
  'name' : string,
  'description' : string,
  'budgetAllocation' : number,
  'projectId' : ProjectId,
  'startDate' : [] | [Timestamp],
}
export interface CreateProjectPayload {
  'name' : string,
  'description' : string,
  'siteLocation' : string,
  'totalBudget' : number,
}
export interface CreateSupplierPayload {
  'materialCategories' : Array<MaterialCategory>,
  'name' : string,
  'contactPerson' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface DeliveryPublic {
  'id' : bigint,
  'status' : DeliveryStatus,
  'createdAt' : Timestamp,
  'actualDate' : [] | [Timestamp],
  'updatedAt' : Timestamp,
  'projectId' : ProjectId,
  'notes' : [] | [string],
  'expectedDate' : Timestamp,
  'supplierId' : SupplierId,
}
export type DeliveryStatus = { 'InTransit' : null } |
  { 'Delivered' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export interface InventoryBalance {
  'isBelowThreshold' : boolean,
  'unit' : string,
  'materialId' : MaterialId,
  'projectId' : ProjectId,
  'category' : MaterialCategory,
  'currentStock' : number,
  'materialName' : string,
  'reorderThreshold' : number,
}
export interface InventoryTransaction {
  'id' : TransactionId,
  'transactionDate' : Timestamp,
  'transactionType' : TransactionType,
  'createdAt' : Timestamp,
  'invoiceId' : [] | [InvoiceId],
  'totalCost' : number,
  'materialId' : MaterialId,
  'recordedBy' : UserId,
  'projectId' : ProjectId,
  'notes' : [] | [string],
  'quantity' : number,
  'supplierId' : [] | [SupplierId],
  'phaseId' : [] | [PhaseId],
  'unitCost' : number,
  'qrCode' : [] | [string],
}
export type InvoiceId = bigint;
export interface InvoiceLineItem {
  'totalCost' : number,
  'description' : string,
  'materialId' : [] | [MaterialId],
  'quantity' : number,
  'unitCost' : number,
}
export interface InvoicePublic {
  'id' : InvoiceId,
  'status' : InvoiceStatus,
  'lineItems' : Array<InvoiceLineItem>,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'dueDate' : [] | [Timestamp],
  'updatedAt' : Timestamp,
  'invoiceType' : InvoiceType,
  'projectId' : ProjectId,
  'totalAmount' : number,
  'notes' : [] | [string],
  'paidAt' : [] | [Timestamp],
  'supplierId' : [] | [SupplierId],
}
export type InvoiceStatus = { 'Paid' : null } |
  { 'Draft' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export type InvoiceType = { 'SupplierDelivery' : null } |
  { 'Manual' : null };
export interface LogInflowPayload {
  'transactionDate' : Timestamp,
  'materialId' : MaterialId,
  'projectId' : ProjectId,
  'notes' : [] | [string],
  'quantity' : number,
  'supplierId' : [] | [SupplierId],
  'phaseId' : [] | [PhaseId],
  'unitCost' : number,
  'qrCode' : [] | [string],
}
export interface LogOutflowPayload {
  'transactionDate' : Timestamp,
  'materialId' : MaterialId,
  'projectId' : ProjectId,
  'notes' : [] | [string],
  'quantity' : number,
  'phaseId' : [] | [PhaseId],
  'unitCost' : number,
  'qrCode' : [] | [string],
}
export type MaterialCategory = { 'Steel' : null } |
  { 'Plumbing' : null } |
  { 'Sand' : null } |
  { 'Cement' : null } |
  { 'Wood' : null } |
  { 'Bricks' : null } |
  { 'Aggregate' : null } |
  { 'Paint' : null } |
  { 'Electrical' : null } |
  { 'Other' : null };
export type MaterialId = bigint;
export interface MaterialPublic {
  'id' : MaterialId,
  'name' : string,
  'createdAt' : Timestamp,
  'unit' : string,
  'updatedAt' : Timestamp,
  'projectId' : ProjectId,
  'category' : MaterialCategory,
  'currentStock' : number,
  'reorderThreshold' : number,
}
export interface MaterialSpending {
  'totalCost' : number,
  'materialId' : MaterialId,
  'materialName' : string,
  'totalQuantity' : number,
}
export type PhaseId = bigint;
export interface PhasePublic {
  'id' : PhaseId,
  'status' : PhaseStatus,
  'endDate' : [] | [Timestamp],
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'budgetAllocation' : number,
  'projectId' : ProjectId,
  'startDate' : [] | [Timestamp],
}
export interface PhaseSpending {
  'totalSpent' : number,
  'phaseName' : string,
  'phaseId' : PhaseId,
}
export type PhaseStatus = { 'Planned' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export type ProjectId = bigint;
export interface ProjectPublic {
  'id' : ProjectId,
  'status' : ProjectStatus,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'siteLocation' : string,
  'updatedAt' : Timestamp,
  'totalBudget' : number,
}
export type ProjectStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'Completed' : null };
export interface RegisterUserPayload {
  'name' : string,
  'role' : Role,
  'email' : string,
}
export type Role = { 'ProjectManager' : null } |
  { 'Admin' : null } |
  { 'SiteEngineer' : null } |
  { 'FinanceProcurement' : null };
export interface SpendingReport {
  'phaseBreakdown' : Array<PhaseSpending>,
  'projectName' : string,
  'materialBreakdown' : Array<MaterialSpending>,
  'reportGeneratedAt' : Timestamp,
  'totalSpent' : number,
  'projectId' : ProjectId,
}
export type SupplierId = bigint;
export interface SupplierPublic {
  'id' : SupplierId,
  'materialCategories' : Array<MaterialCategory>,
  'name' : string,
  'createdAt' : Timestamp,
  'contactPerson' : string,
  'isActive' : boolean,
  'email' : string,
  'updatedAt' : Timestamp,
  'address' : string,
  'phone' : string,
}
export type Timestamp = bigint;
export type TransactionId = bigint;
export type TransactionType = { 'Outflow' : null } |
  { 'Inflow' : null };
export interface UpdateBudgetPayload {
  'notes' : [] | [string],
  'allocatedAmount' : [] | [number],
}
export interface UpdateInvoiceStatusPayload {
  'status' : InvoiceStatus,
  'invoiceId' : InvoiceId,
}
export interface UpdateProjectPayload {
  'status' : [] | [ProjectStatus],
  'name' : [] | [string],
  'description' : [] | [string],
  'siteLocation' : [] | [string],
  'totalBudget' : [] | [number],
}
export type UserId = Principal;
export interface UserPublic {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'isActive' : boolean,
  'email' : string,
}
export interface _SERVICE {
  'acknowledgeAlert' : ActorMethod<[AlertId], AlertPublic>,
  'createBudget' : ActorMethod<[CreateBudgetPayload], BudgetPublic>,
  'createDelivery' : ActorMethod<[CreateDeliveryPayload], DeliveryPublic>,
  'createInvoice' : ActorMethod<[CreateInvoicePayload], InvoicePublic>,
  'createMaterial' : ActorMethod<[CreateMaterialPayload], MaterialPublic>,
  'createPhase' : ActorMethod<[CreatePhasePayload], PhasePublic>,
  'createProject' : ActorMethod<[CreateProjectPayload], ProjectPublic>,
  'createSupplier' : ActorMethod<[CreateSupplierPayload], SupplierPublic>,
  'getBudgetVariance' : ActorMethod<[ProjectId], BudgetVariance>,
  'getBudgetsByProject' : ActorMethod<[ProjectId], Array<BudgetPublic>>,
  'getInventoryBalance' : ActorMethod<[ProjectId], Array<InventoryBalance>>,
  'getInvoice' : ActorMethod<[InvoiceId], [] | [InvoicePublic]>,
  'getMaterialByQrCode' : ActorMethod<[string], [] | [InventoryTransaction]>,
  'getMyProfile' : ActorMethod<[], [] | [UserPublic]>,
  'getPendingInvoices' : ActorMethod<[[] | [ProjectId]], Array<InvoicePublic>>,
  'getProject' : ActorMethod<[ProjectId], [] | [ProjectPublic]>,
  'getSpendingReport' : ActorMethod<[ProjectId], SpendingReport>,
  'getSupplier' : ActorMethod<[SupplierId], [] | [SupplierPublic]>,
  'isUserRegistered' : ActorMethod<[], boolean>,
  'listAlerts' : ActorMethod<[[] | [ProjectId], boolean], Array<AlertPublic>>,
  'listDeliveries' : ActorMethod<
    [[] | [SupplierId], [] | [ProjectId], [] | [DeliveryStatus]],
    Array<DeliveryPublic>
  >,
  'listInventoryTransactions' : ActorMethod<
    [[] | [ProjectId], [] | [MaterialId], [] | [TransactionType]],
    Array<InventoryTransaction>
  >,
  'listInvoices' : ActorMethod<
    [[] | [ProjectId], [] | [SupplierId], [] | [InvoiceStatus]],
    Array<InvoicePublic>
  >,
  'listMaterials' : ActorMethod<[[] | [ProjectId]], Array<MaterialPublic>>,
  'listPhasesByProject' : ActorMethod<[ProjectId], Array<PhasePublic>>,
  'listProjects' : ActorMethod<[[] | [ProjectStatus]], Array<ProjectPublic>>,
  'listSuppliers' : ActorMethod<[], Array<SupplierPublic>>,
  'listUsers' : ActorMethod<[], Array<UserPublic>>,
  'logMaterialInflow' : ActorMethod<[LogInflowPayload], InventoryTransaction>,
  'logMaterialOutflow' : ActorMethod<[LogOutflowPayload], InventoryTransaction>,
  'registerUser' : ActorMethod<[RegisterUserPayload], UserPublic>,
  'runAlertChecks' : ActorMethod<[], bigint>,
  'updateBudget' : ActorMethod<[BudgetId, UpdateBudgetPayload], BudgetPublic>,
  'updateDeliveryStatus' : ActorMethod<
    [bigint, DeliveryStatus, [] | [Timestamp]],
    DeliveryPublic
  >,
  'updateInvoiceStatus' : ActorMethod<
    [UpdateInvoiceStatusPayload],
    InvoicePublic
  >,
  'updateProject' : ActorMethod<
    [ProjectId, UpdateProjectPayload],
    ProjectPublic
  >,
  'updateUserRole' : ActorMethod<[UserId, Role], UserPublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];