/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InvoicePublic {
    id: InvoiceId;
    status: InvoiceStatus;
    lineItems: Array<InvoiceLineItem>;
    createdAt: Timestamp;
    createdBy: UserId;
    dueDate?: Timestamp;
    updatedAt: Timestamp;
    invoiceType: InvoiceType;
    projectId: ProjectId;
    totalAmount: number;
    notes?: string;
    paidAt?: Timestamp;
    supplierId?: SupplierId;
}
export interface BudgetVariance {
    totalAllocated: number;
    projectName: string;
    categoryBreakdown: Array<CategoryVariance>;
    variancePercent: number;
    variance: number;
    totalSpent: number;
    projectId: ProjectId;
    isOverrun: boolean;
}
export type Timestamp = bigint;
export interface MaterialPublic {
    id: MaterialId;
    name: string;
    createdAt: Timestamp;
    unit: string;
    updatedAt: Timestamp;
    projectId: ProjectId;
    category: MaterialCategory;
    currentStock: number;
    reorderThreshold: number;
}
export interface UserPublic {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    isActive: boolean;
    email: string;
}
export interface PhaseSpending {
    totalSpent: number;
    phaseName: string;
    phaseId: PhaseId;
}
export interface BudgetPublic {
    id: BudgetId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    projectId: ProjectId;
    notes?: string;
    allocatedAmount: number;
    category: BudgetCategory;
    spentAmount: number;
}
export type BudgetId = bigint;
export interface InventoryTransaction {
    id: TransactionId;
    transactionDate: Timestamp;
    transactionType: TransactionType;
    createdAt: Timestamp;
    invoiceId?: InvoiceId;
    totalCost: number;
    materialId: MaterialId;
    recordedBy: UserId;
    projectId: ProjectId;
    notes?: string;
    quantity: number;
    supplierId?: SupplierId;
    phaseId?: PhaseId;
    unitCost: number;
    qrCode?: string;
}
export interface CreateDeliveryPayload {
    projectId: ProjectId;
    notes?: string;
    expectedDate: Timestamp;
    supplierId: SupplierId;
}
export interface SpendingReport {
    phaseBreakdown: Array<PhaseSpending>;
    projectName: string;
    materialBreakdown: Array<MaterialSpending>;
    reportGeneratedAt: Timestamp;
    totalSpent: number;
    projectId: ProjectId;
}
export interface SupplierPublic {
    id: SupplierId;
    materialCategories: Array<MaterialCategory>;
    name: string;
    createdAt: Timestamp;
    contactPerson: string;
    isActive: boolean;
    email: string;
    updatedAt: Timestamp;
    address: string;
    phone: string;
}
export type TransactionId = bigint;
export interface MaterialSpending {
    totalCost: number;
    materialId: MaterialId;
    materialName: string;
    totalQuantity: number;
}
export interface ProjectPublic {
    id: ProjectId;
    status: ProjectStatus;
    name: string;
    createdAt: Timestamp;
    createdBy: UserId;
    description: string;
    siteLocation: string;
    updatedAt: Timestamp;
    totalBudget: number;
}
export interface DeliveryPublic {
    id: bigint;
    status: DeliveryStatus;
    createdAt: Timestamp;
    actualDate?: Timestamp;
    updatedAt: Timestamp;
    projectId: ProjectId;
    notes?: string;
    expectedDate: Timestamp;
    supplierId: SupplierId;
}
export type SupplierId = bigint;
export interface UpdateInvoiceStatusPayload {
    status: InvoiceStatus;
    invoiceId: InvoiceId;
}
export interface RegisterUserPayload {
    name: string;
    role: Role;
    email: string;
}
export interface LogOutflowPayload {
    transactionDate: Timestamp;
    materialId: MaterialId;
    projectId: ProjectId;
    notes?: string;
    quantity: number;
    phaseId?: PhaseId;
    unitCost: number;
    qrCode?: string;
}
export interface CreateMaterialPayload {
    name: string;
    unit: string;
    projectId: ProjectId;
    category: MaterialCategory;
    reorderThreshold: number;
}
export interface AlertPublic {
    id: AlertId;
    alertType: AlertType;
    acknowledgedAt?: Timestamp;
    acknowledgedBy?: UserId;
    createdAt: Timestamp;
    isAcknowledged: boolean;
    relatedEntityId: bigint;
    projectId: ProjectId;
    message: string;
    severity: AlertSeverity;
}
export interface InventoryBalance {
    isBelowThreshold: boolean;
    unit: string;
    materialId: MaterialId;
    projectId: ProjectId;
    category: MaterialCategory;
    currentStock: number;
    materialName: string;
    reorderThreshold: number;
}
export interface CreateSupplierPayload {
    materialCategories: Array<MaterialCategory>;
    name: string;
    contactPerson: string;
    email: string;
    address: string;
    phone: string;
}
export type PhaseId = bigint;
export interface CreateProjectPayload {
    name: string;
    description: string;
    siteLocation: string;
    totalBudget: number;
}
export interface CategoryVariance {
    allocated: number;
    variance: number;
    spent: number;
    category: BudgetCategory;
}
export interface PhasePublic {
    id: PhaseId;
    status: PhaseStatus;
    endDate?: Timestamp;
    name: string;
    createdAt: Timestamp;
    description: string;
    budgetAllocation: number;
    projectId: ProjectId;
    startDate?: Timestamp;
}
export interface CreateInvoicePayload {
    lineItems: Array<InvoiceLineItem>;
    dueDate?: Timestamp;
    projectId: ProjectId;
    notes?: string;
    supplierId?: SupplierId;
}
export type AlertId = bigint;
export interface UpdateProjectPayload {
    status?: ProjectStatus;
    name?: string;
    description?: string;
    siteLocation?: string;
    totalBudget?: number;
}
export type MaterialId = bigint;
export type UserId = Principal;
export type ProjectId = bigint;
export interface LogInflowPayload {
    transactionDate: Timestamp;
    materialId: MaterialId;
    projectId: ProjectId;
    notes?: string;
    quantity: number;
    supplierId?: SupplierId;
    phaseId?: PhaseId;
    unitCost: number;
    qrCode?: string;
}
export type InvoiceId = bigint;
export interface UpdateBudgetPayload {
    notes?: string;
    allocatedAmount?: number;
}
export interface CreatePhasePayload {
    endDate?: Timestamp;
    name: string;
    description: string;
    budgetAllocation: number;
    projectId: ProjectId;
    startDate?: Timestamp;
}
export interface InvoiceLineItem {
    totalCost: number;
    description: string;
    materialId?: MaterialId;
    quantity: number;
    unitCost: number;
}
export interface CreateBudgetPayload {
    projectId: ProjectId;
    notes?: string;
    allocatedAmount: number;
    category: BudgetCategory;
}
export enum AlertSeverity {
    Info = "Info",
    Critical = "Critical",
    Warning = "Warning"
}
export enum AlertType {
    BudgetOverrun = "BudgetOverrun",
    PendingInvoice = "PendingInvoice",
    LowInventory = "LowInventory"
}
export enum BudgetCategory {
    Labor = "Labor",
    Overhead = "Overhead",
    Materials = "Materials",
    Other = "Other",
    Equipment = "Equipment"
}
export enum DeliveryStatus {
    InTransit = "InTransit",
    Delivered = "Delivered",
    Cancelled = "Cancelled",
    Pending = "Pending"
}
export enum InvoiceStatus {
    Paid = "Paid",
    Draft = "Draft",
    Cancelled = "Cancelled",
    Pending = "Pending"
}
export enum InvoiceType {
    SupplierDelivery = "SupplierDelivery",
    Manual = "Manual"
}
export enum MaterialCategory {
    Steel = "Steel",
    Plumbing = "Plumbing",
    Sand = "Sand",
    Cement = "Cement",
    Wood = "Wood",
    Bricks = "Bricks",
    Aggregate = "Aggregate",
    Paint = "Paint",
    Electrical = "Electrical",
    Other = "Other"
}
export enum PhaseStatus {
    Planned = "Planned",
    InProgress = "InProgress",
    Completed = "Completed"
}
export enum ProjectStatus {
    Inactive = "Inactive",
    Active = "Active",
    Completed = "Completed"
}
export enum Role {
    ProjectManager = "ProjectManager",
    Admin = "Admin",
    SiteEngineer = "SiteEngineer",
    FinanceProcurement = "FinanceProcurement"
}
export enum TransactionType {
    Outflow = "Outflow",
    Inflow = "Inflow"
}
export interface backendInterface {
    acknowledgeAlert(alertId: AlertId): Promise<AlertPublic>;
    createBudget(payload: CreateBudgetPayload): Promise<BudgetPublic>;
    createDelivery(payload: CreateDeliveryPayload): Promise<DeliveryPublic>;
    createInvoice(payload: CreateInvoicePayload): Promise<InvoicePublic>;
    createMaterial(payload: CreateMaterialPayload): Promise<MaterialPublic>;
    createPhase(payload: CreatePhasePayload): Promise<PhasePublic>;
    createProject(payload: CreateProjectPayload): Promise<ProjectPublic>;
    createSupplier(payload: CreateSupplierPayload): Promise<SupplierPublic>;
    getBudgetVariance(projectId: ProjectId): Promise<BudgetVariance>;
    getBudgetsByProject(projectId: ProjectId): Promise<Array<BudgetPublic>>;
    getInventoryBalance(projectId: ProjectId): Promise<Array<InventoryBalance>>;
    getInvoice(invoiceId: InvoiceId): Promise<InvoicePublic | null>;
    getMaterialByQrCode(qrCode: string): Promise<InventoryTransaction | null>;
    getMyProfile(): Promise<UserPublic | null>;
    getPendingInvoices(projectId: ProjectId | null): Promise<Array<InvoicePublic>>;
    getProject(projectId: ProjectId): Promise<ProjectPublic | null>;
    getSpendingReport(projectId: ProjectId): Promise<SpendingReport>;
    getSupplier(supplierId: SupplierId): Promise<SupplierPublic | null>;
    isUserRegistered(): Promise<boolean>;
    listAlerts(projectId: ProjectId | null, onlyUnacknowledged: boolean): Promise<Array<AlertPublic>>;
    listDeliveries(supplierId: SupplierId | null, projectId: ProjectId | null, status: DeliveryStatus | null): Promise<Array<DeliveryPublic>>;
    listInventoryTransactions(projectId: ProjectId | null, materialId: MaterialId | null, txType: TransactionType | null): Promise<Array<InventoryTransaction>>;
    listInvoices(projectId: ProjectId | null, supplierId: SupplierId | null, status: InvoiceStatus | null): Promise<Array<InvoicePublic>>;
    listMaterials(projectId: ProjectId | null): Promise<Array<MaterialPublic>>;
    listPhasesByProject(projectId: ProjectId): Promise<Array<PhasePublic>>;
    listProjects(statusFilter: ProjectStatus | null): Promise<Array<ProjectPublic>>;
    listSuppliers(): Promise<Array<SupplierPublic>>;
    listUsers(): Promise<Array<UserPublic>>;
    logMaterialInflow(payload: LogInflowPayload): Promise<InventoryTransaction>;
    logMaterialOutflow(payload: LogOutflowPayload): Promise<InventoryTransaction>;
    registerUser(payload: RegisterUserPayload): Promise<UserPublic>;
    runAlertChecks(): Promise<bigint>;
    updateBudget(budgetId: BudgetId, payload: UpdateBudgetPayload): Promise<BudgetPublic>;
    updateDeliveryStatus(deliveryId: bigint, status: DeliveryStatus, actualDate: Timestamp | null): Promise<DeliveryPublic>;
    updateInvoiceStatus(payload: UpdateInvoiceStatusPayload): Promise<InvoicePublic>;
    updateProject(projectId: ProjectId, payload: UpdateProjectPayload): Promise<ProjectPublic>;
    updateUserRole(targetId: UserId, role: Role): Promise<UserPublic>;
}
import type { AlertId as _AlertId, AlertPublic as _AlertPublic, AlertSeverity as _AlertSeverity, AlertType as _AlertType, BudgetCategory as _BudgetCategory, BudgetId as _BudgetId, BudgetPublic as _BudgetPublic, BudgetVariance as _BudgetVariance, CategoryVariance as _CategoryVariance, CreateBudgetPayload as _CreateBudgetPayload, CreateDeliveryPayload as _CreateDeliveryPayload, CreateInvoicePayload as _CreateInvoicePayload, CreateMaterialPayload as _CreateMaterialPayload, CreatePhasePayload as _CreatePhasePayload, CreateSupplierPayload as _CreateSupplierPayload, DeliveryPublic as _DeliveryPublic, DeliveryStatus as _DeliveryStatus, InventoryBalance as _InventoryBalance, InventoryTransaction as _InventoryTransaction, InvoiceId as _InvoiceId, InvoiceLineItem as _InvoiceLineItem, InvoicePublic as _InvoicePublic, InvoiceStatus as _InvoiceStatus, InvoiceType as _InvoiceType, LogInflowPayload as _LogInflowPayload, LogOutflowPayload as _LogOutflowPayload, MaterialCategory as _MaterialCategory, MaterialId as _MaterialId, MaterialPublic as _MaterialPublic, PhaseId as _PhaseId, PhasePublic as _PhasePublic, PhaseStatus as _PhaseStatus, ProjectId as _ProjectId, ProjectPublic as _ProjectPublic, ProjectStatus as _ProjectStatus, RegisterUserPayload as _RegisterUserPayload, Role as _Role, SupplierId as _SupplierId, SupplierPublic as _SupplierPublic, Timestamp as _Timestamp, TransactionId as _TransactionId, TransactionType as _TransactionType, UpdateBudgetPayload as _UpdateBudgetPayload, UpdateInvoiceStatusPayload as _UpdateInvoiceStatusPayload, UpdateProjectPayload as _UpdateProjectPayload, UserId as _UserId, UserPublic as _UserPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acknowledgeAlert(arg0: AlertId): Promise<AlertPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return from_candid_AlertPublic_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return from_candid_AlertPublic_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBudget(arg0: CreateBudgetPayload): Promise<BudgetPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createBudget(to_candid_CreateBudgetPayload_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BudgetPublic_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBudget(to_candid_CreateBudgetPayload_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BudgetPublic_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDelivery(arg0: CreateDeliveryPayload): Promise<DeliveryPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createDelivery(to_candid_CreateDeliveryPayload_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_DeliveryPublic_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDelivery(to_candid_CreateDeliveryPayload_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_DeliveryPublic_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInvoice(arg0: CreateInvoicePayload): Promise<InvoicePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_CreateInvoicePayload_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_InvoicePublic_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_CreateInvoicePayload_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_InvoicePublic_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMaterial(arg0: CreateMaterialPayload): Promise<MaterialPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createMaterial(to_candid_CreateMaterialPayload_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MaterialPublic_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMaterial(to_candid_CreateMaterialPayload_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MaterialPublic_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPhase(arg0: CreatePhasePayload): Promise<PhasePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createPhase(to_candid_CreatePhasePayload_n48(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PhasePublic_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPhase(to_candid_CreatePhasePayload_n48(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PhasePublic_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProject(arg0: CreateProjectPayload): Promise<ProjectPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0);
                return from_candid_ProjectPublic_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0);
            return from_candid_ProjectPublic_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSupplier(arg0: CreateSupplierPayload): Promise<SupplierPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createSupplier(to_candid_CreateSupplierPayload_n58(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SupplierPublic_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSupplier(to_candid_CreateSupplierPayload_n58(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SupplierPublic_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudgetVariance(arg0: ProjectId): Promise<BudgetVariance> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetVariance(arg0);
                return from_candid_BudgetVariance_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetVariance(arg0);
            return from_candid_BudgetVariance_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudgetsByProject(arg0: ProjectId): Promise<Array<BudgetPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudgetsByProject(arg0);
                return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudgetsByProject(arg0);
            return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryBalance(arg0: ProjectId): Promise<Array<InventoryBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryBalance(arg0);
                return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryBalance(arg0);
            return from_candid_vec_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: InvoiceId): Promise<InvoicePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaterialByQrCode(arg0: string): Promise<InventoryTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialByQrCode(arg0);
                return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialByQrCode(arg0);
            return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingInvoices(arg0: ProjectId | null): Promise<Array<InvoicePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingInvoices(to_candid_opt_n86(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingInvoices(to_candid_opt_n86(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: ProjectId): Promise<ProjectPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpendingReport(arg0: ProjectId): Promise<SpendingReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpendingReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpendingReport(arg0);
            return result;
        }
    }
    async getSupplier(arg0: SupplierId): Promise<SupplierPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplier(arg0);
                return from_candid_opt_n89(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplier(arg0);
            return from_candid_opt_n89(this._uploadFile, this._downloadFile, result);
        }
    }
    async isUserRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserRegistered();
            return result;
        }
    }
    async listAlerts(arg0: ProjectId | null, arg1: boolean): Promise<Array<AlertPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAlerts(to_candid_opt_n86(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_vec_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAlerts(to_candid_opt_n86(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_vec_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDeliveries(arg0: SupplierId | null, arg1: ProjectId | null, arg2: DeliveryStatus | null): Promise<Array<DeliveryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDeliveries(to_candid_opt_n91(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n86(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n95(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDeliveries(to_candid_opt_n91(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n86(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n92(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n95(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInventoryTransactions(arg0: ProjectId | null, arg1: MaterialId | null, arg2: TransactionType | null): Promise<Array<InventoryTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInventoryTransactions(to_candid_opt_n86(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n96(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n97(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n100(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInventoryTransactions(to_candid_opt_n86(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n96(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n97(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n100(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInvoices(arg0: ProjectId | null, arg1: SupplierId | null, arg2: InvoiceStatus | null): Promise<Array<InvoicePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoices(to_candid_opt_n86(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n91(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n101(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoices(to_candid_opt_n86(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n91(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n101(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMaterials(arg0: ProjectId | null): Promise<Array<MaterialPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMaterials(to_candid_opt_n86(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n104(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMaterials(to_candid_opt_n86(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n104(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPhasesByProject(arg0: ProjectId): Promise<Array<PhasePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPhasesByProject(arg0);
                return from_candid_vec_n105(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPhasesByProject(arg0);
            return from_candid_vec_n105(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(arg0: ProjectStatus | null): Promise<Array<ProjectPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects(to_candid_opt_n106(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n109(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects(to_candid_opt_n106(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n109(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSuppliers(): Promise<Array<SupplierPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSuppliers();
                return from_candid_vec_n110(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSuppliers();
            return from_candid_vec_n110(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsers(): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n111(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n111(this._uploadFile, this._downloadFile, result);
        }
    }
    async logMaterialInflow(arg0: LogInflowPayload): Promise<InventoryTransaction> {
        if (this.processError) {
            try {
                const result = await this.actor.logMaterialInflow(to_candid_LogInflowPayload_n112(this._uploadFile, this._downloadFile, arg0));
                return from_candid_InventoryTransaction_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMaterialInflow(to_candid_LogInflowPayload_n112(this._uploadFile, this._downloadFile, arg0));
            return from_candid_InventoryTransaction_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async logMaterialOutflow(arg0: LogOutflowPayload): Promise<InventoryTransaction> {
        if (this.processError) {
            try {
                const result = await this.actor.logMaterialOutflow(to_candid_LogOutflowPayload_n114(this._uploadFile, this._downloadFile, arg0));
                return from_candid_InventoryTransaction_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMaterialOutflow(to_candid_LogOutflowPayload_n114(this._uploadFile, this._downloadFile, arg0));
            return from_candid_InventoryTransaction_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: RegisterUserPayload): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_RegisterUserPayload_n116(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserPublic_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_RegisterUserPayload_n116(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserPublic_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async runAlertChecks(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.runAlertChecks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runAlertChecks();
            return result;
        }
    }
    async updateBudget(arg0: BudgetId, arg1: UpdateBudgetPayload): Promise<BudgetPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBudget(arg0, to_candid_UpdateBudgetPayload_n120(this._uploadFile, this._downloadFile, arg1));
                return from_candid_BudgetPublic_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBudget(arg0, to_candid_UpdateBudgetPayload_n120(this._uploadFile, this._downloadFile, arg1));
            return from_candid_BudgetPublic_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDeliveryStatus(arg0: bigint, arg1: DeliveryStatus, arg2: Timestamp | null): Promise<DeliveryPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryStatus(arg0, to_candid_DeliveryStatus_n93(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n122(this._uploadFile, this._downloadFile, arg2));
                return from_candid_DeliveryPublic_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryStatus(arg0, to_candid_DeliveryStatus_n93(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n122(this._uploadFile, this._downloadFile, arg2));
            return from_candid_DeliveryPublic_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInvoiceStatus(arg0: UpdateInvoiceStatusPayload): Promise<InvoicePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoiceStatus(to_candid_UpdateInvoiceStatusPayload_n123(this._uploadFile, this._downloadFile, arg0));
                return from_candid_InvoicePublic_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoiceStatus(to_candid_UpdateInvoiceStatusPayload_n123(this._uploadFile, this._downloadFile, arg0));
            return from_candid_InvoicePublic_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: ProjectId, arg1: UpdateProjectPayload): Promise<ProjectPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_UpdateProjectPayload_n125(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ProjectPublic_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_UpdateProjectPayload_n125(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ProjectPublic_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserRole(arg0: UserId, arg1: Role): Promise<UserPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_Role_n118(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserPublic_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_Role_n118(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserPublic_n82(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AlertPublic_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertPublic): AlertPublic {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_AlertSeverity_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertSeverity): AlertSeverity {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_AlertType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertType): AlertType {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_BudgetCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetCategory): BudgetCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BudgetPublic_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetPublic): BudgetPublic {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_BudgetVariance_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BudgetVariance): BudgetVariance {
    return from_candid_record_n65(_uploadFile, _downloadFile, value);
}
function from_candid_CategoryVariance_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryVariance): CategoryVariance {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryPublic_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryPublic): DeliveryPublic {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryStatus): DeliveryStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryBalance_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryBalance): InventoryBalance {
    return from_candid_record_n72(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryTransaction_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryTransaction): InventoryTransaction {
    return from_candid_record_n76(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceLineItem_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceLineItem): InvoiceLineItem {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_InvoicePublic_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoicePublic): InvoicePublic {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceType): InvoiceType {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_MaterialCategory_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaterialCategory): MaterialCategory {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_MaterialPublic_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaterialPublic): MaterialPublic {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_PhasePublic_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhasePublic): PhasePublic {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_PhaseStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhaseStatus): PhaseStatus {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectPublic_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectPublic): ProjectPublic {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n85(_uploadFile, _downloadFile, value);
}
function from_candid_SupplierPublic_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupplierPublic): SupplierPublic {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n83(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MaterialId]): MaterialId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplierId]): SupplierId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoicePublic]): InvoicePublic | null {
    return value.length === 0 ? null : from_candid_InvoicePublic_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventoryTransaction]): InventoryTransaction | null {
    return value.length === 0 ? null : from_candid_InventoryTransaction_n75(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceId]): InvoiceId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PhaseId]): PhaseId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n82(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectPublic]): ProjectPublic | null {
    return value.length === 0 ? null : from_candid_ProjectPublic_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplierPublic]): SupplierPublic | null {
    return value.length === 0 ? null : from_candid_SupplierPublic_n61(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BudgetId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    projectId: _ProjectId;
    notes: [] | [string];
    allocatedAmount: number;
    category: _BudgetCategory;
    spentAmount: number;
}): {
    id: BudgetId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    projectId: ProjectId;
    notes?: string;
    allocatedAmount: number;
    category: BudgetCategory;
    spentAmount: number;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        projectId: value.projectId,
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        allocatedAmount: value.allocatedAmount,
        category: from_candid_BudgetCategory_n16(_uploadFile, _downloadFile, value.category),
        spentAmount: value.spentAmount
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AlertId;
    alertType: _AlertType;
    acknowledgedAt: [] | [_Timestamp];
    acknowledgedBy: [] | [_UserId];
    createdAt: _Timestamp;
    isAcknowledged: boolean;
    relatedEntityId: bigint;
    projectId: _ProjectId;
    message: string;
    severity: _AlertSeverity;
}): {
    id: AlertId;
    alertType: AlertType;
    acknowledgedAt?: Timestamp;
    acknowledgedBy?: UserId;
    createdAt: Timestamp;
    isAcknowledged: boolean;
    relatedEntityId: bigint;
    projectId: ProjectId;
    message: string;
    severity: AlertSeverity;
} {
    return {
        id: value.id,
        alertType: from_candid_AlertType_n3(_uploadFile, _downloadFile, value.alertType),
        acknowledgedAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.acknowledgedAt)),
        acknowledgedBy: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.acknowledgedBy)),
        createdAt: value.createdAt,
        isAcknowledged: value.isAcknowledged,
        relatedEntityId: value.relatedEntityId,
        projectId: value.projectId,
        message: value.message,
        severity: from_candid_AlertSeverity_n7(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DeliveryStatus;
    createdAt: _Timestamp;
    actualDate: [] | [_Timestamp];
    updatedAt: _Timestamp;
    projectId: _ProjectId;
    notes: [] | [string];
    expectedDate: _Timestamp;
    supplierId: _SupplierId;
}): {
    id: bigint;
    status: DeliveryStatus;
    createdAt: Timestamp;
    actualDate?: Timestamp;
    updatedAt: Timestamp;
    projectId: ProjectId;
    notes?: string;
    expectedDate: Timestamp;
    supplierId: SupplierId;
} {
    return {
        id: value.id,
        status: from_candid_DeliveryStatus_n22(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        actualDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.actualDate)),
        updatedAt: value.updatedAt,
        projectId: value.projectId,
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        expectedDate: value.expectedDate,
        supplierId: value.supplierId
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InvoiceId;
    status: _InvoiceStatus;
    lineItems: Array<_InvoiceLineItem>;
    createdAt: _Timestamp;
    createdBy: _UserId;
    dueDate: [] | [_Timestamp];
    updatedAt: _Timestamp;
    invoiceType: _InvoiceType;
    projectId: _ProjectId;
    totalAmount: number;
    notes: [] | [string];
    paidAt: [] | [_Timestamp];
    supplierId: [] | [_SupplierId];
}): {
    id: InvoiceId;
    status: InvoiceStatus;
    lineItems: Array<InvoiceLineItem>;
    createdAt: Timestamp;
    createdBy: UserId;
    dueDate?: Timestamp;
    updatedAt: Timestamp;
    invoiceType: InvoiceType;
    projectId: ProjectId;
    totalAmount: number;
    notes?: string;
    paidAt?: Timestamp;
    supplierId?: SupplierId;
} {
    return {
        id: value.id,
        status: from_candid_InvoiceStatus_n31(_uploadFile, _downloadFile, value.status),
        lineItems: from_candid_vec_n33(_uploadFile, _downloadFile, value.lineItems),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        dueDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.dueDate)),
        updatedAt: value.updatedAt,
        invoiceType: from_candid_InvoiceType_n37(_uploadFile, _downloadFile, value.invoiceType),
        projectId: value.projectId,
        totalAmount: value.totalAmount,
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        paidAt: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.paidAt)),
        supplierId: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.supplierId))
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCost: number;
    description: string;
    materialId: [] | [_MaterialId];
    quantity: number;
    unitCost: number;
}): {
    totalCost: number;
    description: string;
    materialId?: MaterialId;
    quantity: number;
    unitCost: number;
} {
    return {
        totalCost: value.totalCost,
        description: value.description,
        materialId: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.materialId)),
        quantity: value.quantity,
        unitCost: value.unitCost
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MaterialId;
    name: string;
    createdAt: _Timestamp;
    unit: string;
    updatedAt: _Timestamp;
    projectId: _ProjectId;
    category: _MaterialCategory;
    currentStock: number;
    reorderThreshold: number;
}): {
    id: MaterialId;
    name: string;
    createdAt: Timestamp;
    unit: string;
    updatedAt: Timestamp;
    projectId: ProjectId;
    category: MaterialCategory;
    currentStock: number;
    reorderThreshold: number;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        unit: value.unit,
        updatedAt: value.updatedAt,
        projectId: value.projectId,
        category: from_candid_MaterialCategory_n46(_uploadFile, _downloadFile, value.category),
        currentStock: value.currentStock,
        reorderThreshold: value.reorderThreshold
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PhaseId;
    status: _PhaseStatus;
    endDate: [] | [_Timestamp];
    name: string;
    createdAt: _Timestamp;
    description: string;
    budgetAllocation: number;
    projectId: _ProjectId;
    startDate: [] | [_Timestamp];
}): {
    id: PhaseId;
    status: PhaseStatus;
    endDate?: Timestamp;
    name: string;
    createdAt: Timestamp;
    description: string;
    budgetAllocation: number;
    projectId: ProjectId;
    startDate?: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_PhaseStatus_n52(_uploadFile, _downloadFile, value.status),
        endDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.endDate)),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        budgetAllocation: value.budgetAllocation,
        projectId: value.projectId,
        startDate: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.startDate))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    status: _ProjectStatus;
    name: string;
    createdAt: _Timestamp;
    createdBy: _UserId;
    description: string;
    siteLocation: string;
    updatedAt: _Timestamp;
    totalBudget: number;
}): {
    id: ProjectId;
    status: ProjectStatus;
    name: string;
    createdAt: Timestamp;
    createdBy: UserId;
    description: string;
    siteLocation: string;
    updatedAt: Timestamp;
    totalBudget: number;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n56(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        siteLocation: value.siteLocation,
        updatedAt: value.updatedAt,
        totalBudget: value.totalBudget
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SupplierId;
    materialCategories: Array<_MaterialCategory>;
    name: string;
    createdAt: _Timestamp;
    contactPerson: string;
    isActive: boolean;
    email: string;
    updatedAt: _Timestamp;
    address: string;
    phone: string;
}): {
    id: SupplierId;
    materialCategories: Array<MaterialCategory>;
    name: string;
    createdAt: Timestamp;
    contactPerson: string;
    isActive: boolean;
    email: string;
    updatedAt: Timestamp;
    address: string;
    phone: string;
} {
    return {
        id: value.id,
        materialCategories: from_candid_vec_n63(_uploadFile, _downloadFile, value.materialCategories),
        name: value.name,
        createdAt: value.createdAt,
        contactPerson: value.contactPerson,
        isActive: value.isActive,
        email: value.email,
        updatedAt: value.updatedAt,
        address: value.address,
        phone: value.phone
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalAllocated: number;
    projectName: string;
    categoryBreakdown: Array<_CategoryVariance>;
    variancePercent: number;
    variance: number;
    totalSpent: number;
    projectId: _ProjectId;
    isOverrun: boolean;
}): {
    totalAllocated: number;
    projectName: string;
    categoryBreakdown: Array<CategoryVariance>;
    variancePercent: number;
    variance: number;
    totalSpent: number;
    projectId: ProjectId;
    isOverrun: boolean;
} {
    return {
        totalAllocated: value.totalAllocated,
        projectName: value.projectName,
        categoryBreakdown: from_candid_vec_n66(_uploadFile, _downloadFile, value.categoryBreakdown),
        variancePercent: value.variancePercent,
        variance: value.variance,
        totalSpent: value.totalSpent,
        projectId: value.projectId,
        isOverrun: value.isOverrun
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    allocated: number;
    variance: number;
    spent: number;
    category: _BudgetCategory;
}): {
    allocated: number;
    variance: number;
    spent: number;
    category: BudgetCategory;
} {
    return {
        allocated: value.allocated,
        variance: value.variance,
        spent: value.spent,
        category: from_candid_BudgetCategory_n16(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isBelowThreshold: boolean;
    unit: string;
    materialId: _MaterialId;
    projectId: _ProjectId;
    category: _MaterialCategory;
    currentStock: number;
    materialName: string;
    reorderThreshold: number;
}): {
    isBelowThreshold: boolean;
    unit: string;
    materialId: MaterialId;
    projectId: ProjectId;
    category: MaterialCategory;
    currentStock: number;
    materialName: string;
    reorderThreshold: number;
} {
    return {
        isBelowThreshold: value.isBelowThreshold,
        unit: value.unit,
        materialId: value.materialId,
        projectId: value.projectId,
        category: from_candid_MaterialCategory_n46(_uploadFile, _downloadFile, value.category),
        currentStock: value.currentStock,
        materialName: value.materialName,
        reorderThreshold: value.reorderThreshold
    };
}
function from_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    transactionDate: _Timestamp;
    transactionType: _TransactionType;
    createdAt: _Timestamp;
    invoiceId: [] | [_InvoiceId];
    totalCost: number;
    materialId: _MaterialId;
    recordedBy: _UserId;
    projectId: _ProjectId;
    notes: [] | [string];
    quantity: number;
    supplierId: [] | [_SupplierId];
    phaseId: [] | [_PhaseId];
    unitCost: number;
    qrCode: [] | [string];
}): {
    id: TransactionId;
    transactionDate: Timestamp;
    transactionType: TransactionType;
    createdAt: Timestamp;
    invoiceId?: InvoiceId;
    totalCost: number;
    materialId: MaterialId;
    recordedBy: UserId;
    projectId: ProjectId;
    notes?: string;
    quantity: number;
    supplierId?: SupplierId;
    phaseId?: PhaseId;
    unitCost: number;
    qrCode?: string;
} {
    return {
        id: value.id,
        transactionDate: value.transactionDate,
        transactionType: from_candid_TransactionType_n77(_uploadFile, _downloadFile, value.transactionType),
        createdAt: value.createdAt,
        invoiceId: record_opt_to_undefined(from_candid_opt_n79(_uploadFile, _downloadFile, value.invoiceId)),
        totalCost: value.totalCost,
        materialId: value.materialId,
        recordedBy: value.recordedBy,
        projectId: value.projectId,
        notes: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.notes)),
        quantity: value.quantity,
        supplierId: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.supplierId)),
        phaseId: record_opt_to_undefined(from_candid_opt_n80(_uploadFile, _downloadFile, value.phaseId)),
        unitCost: value.unitCost,
        qrCode: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.qrCode))
    };
}
function from_candid_record_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    isActive: boolean;
    email: string;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: Role;
    isActive: boolean;
    email: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n84(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Labor: null;
} | {
    Overhead: null;
} | {
    Materials: null;
} | {
    Other: null;
} | {
    Equipment: null;
}): BudgetCategory {
    return "Labor" in value ? BudgetCategory.Labor : "Overhead" in value ? BudgetCategory.Overhead : "Materials" in value ? BudgetCategory.Materials : "Other" in value ? BudgetCategory.Other : "Equipment" in value ? BudgetCategory.Equipment : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InTransit: null;
} | {
    Delivered: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
}): DeliveryStatus {
    return "InTransit" in value ? DeliveryStatus.InTransit : "Delivered" in value ? DeliveryStatus.Delivered : "Cancelled" in value ? DeliveryStatus.Cancelled : "Pending" in value ? DeliveryStatus.Pending : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paid: null;
} | {
    Draft: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
}): InvoiceStatus {
    return "Paid" in value ? InvoiceStatus.Paid : "Draft" in value ? InvoiceStatus.Draft : "Cancelled" in value ? InvoiceStatus.Cancelled : "Pending" in value ? InvoiceStatus.Pending : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SupplierDelivery: null;
} | {
    Manual: null;
}): InvoiceType {
    return "SupplierDelivery" in value ? InvoiceType.SupplierDelivery : "Manual" in value ? InvoiceType.Manual : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BudgetOverrun: null;
} | {
    PendingInvoice: null;
} | {
    LowInventory: null;
}): AlertType {
    return "BudgetOverrun" in value ? AlertType.BudgetOverrun : "PendingInvoice" in value ? AlertType.PendingInvoice : "LowInventory" in value ? AlertType.LowInventory : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Steel: null;
} | {
    Plumbing: null;
} | {
    Sand: null;
} | {
    Cement: null;
} | {
    Wood: null;
} | {
    Bricks: null;
} | {
    Aggregate: null;
} | {
    Paint: null;
} | {
    Electrical: null;
} | {
    Other: null;
}): MaterialCategory {
    return "Steel" in value ? MaterialCategory.Steel : "Plumbing" in value ? MaterialCategory.Plumbing : "Sand" in value ? MaterialCategory.Sand : "Cement" in value ? MaterialCategory.Cement : "Wood" in value ? MaterialCategory.Wood : "Bricks" in value ? MaterialCategory.Bricks : "Aggregate" in value ? MaterialCategory.Aggregate : "Paint" in value ? MaterialCategory.Paint : "Electrical" in value ? MaterialCategory.Electrical : "Other" in value ? MaterialCategory.Other : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Planned: null;
} | {
    InProgress: null;
} | {
    Completed: null;
}): PhaseStatus {
    return "Planned" in value ? PhaseStatus.Planned : "InProgress" in value ? PhaseStatus.InProgress : "Completed" in value ? PhaseStatus.Completed : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
} | {
    Completed: null;
}): ProjectStatus {
    return "Inactive" in value ? ProjectStatus.Inactive : "Active" in value ? ProjectStatus.Active : "Completed" in value ? ProjectStatus.Completed : value;
}
function from_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Outflow: null;
} | {
    Inflow: null;
}): TransactionType {
    return "Outflow" in value ? TransactionType.Outflow : "Inflow" in value ? TransactionType.Inflow : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Info: null;
} | {
    Critical: null;
} | {
    Warning: null;
}): AlertSeverity {
    return "Info" in value ? AlertSeverity.Info : "Critical" in value ? AlertSeverity.Critical : "Warning" in value ? AlertSeverity.Warning : value;
}
function from_candid_variant_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ProjectManager: null;
} | {
    Admin: null;
} | {
    SiteEngineer: null;
} | {
    FinanceProcurement: null;
}): Role {
    return "ProjectManager" in value ? Role.ProjectManager : "Admin" in value ? Role.Admin : "SiteEngineer" in value ? Role.SiteEngineer : "FinanceProcurement" in value ? Role.FinanceProcurement : value;
}
function from_candid_vec_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryTransaction>): Array<InventoryTransaction> {
    return value.map((x)=>from_candid_InventoryTransaction_n75(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n104(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MaterialPublic>): Array<MaterialPublic> {
    return value.map((x)=>from_candid_MaterialPublic_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n105(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PhasePublic>): Array<PhasePublic> {
    return value.map((x)=>from_candid_PhasePublic_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n109(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectPublic>): Array<ProjectPublic> {
    return value.map((x)=>from_candid_ProjectPublic_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n110(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SupplierPublic>): Array<SupplierPublic> {
    return value.map((x)=>from_candid_SupplierPublic_n61(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n111(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserPublic>): Array<UserPublic> {
    return value.map((x)=>from_candid_UserPublic_n82(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvoiceLineItem>): Array<InvoiceLineItem> {
    return value.map((x)=>from_candid_InvoiceLineItem_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MaterialCategory>): Array<MaterialCategory> {
    return value.map((x)=>from_candid_MaterialCategory_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryVariance>): Array<CategoryVariance> {
    return value.map((x)=>from_candid_CategoryVariance_n67(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BudgetPublic>): Array<BudgetPublic> {
    return value.map((x)=>from_candid_BudgetPublic_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryBalance>): Array<InventoryBalance> {
    return value.map((x)=>from_candid_InventoryBalance_n71(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvoicePublic>): Array<InvoicePublic> {
    return value.map((x)=>from_candid_InvoicePublic_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlertPublic>): Array<AlertPublic> {
    return value.map((x)=>from_candid_AlertPublic_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeliveryPublic>): Array<DeliveryPublic> {
    return value.map((x)=>from_candid_DeliveryPublic_n20(_uploadFile, _downloadFile, x));
}
function to_candid_BudgetCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetCategory): _BudgetCategory {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_CreateBudgetPayload_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBudgetPayload): _CreateBudgetPayload {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_CreateDeliveryPayload_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateDeliveryPayload): _CreateDeliveryPayload {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_CreateInvoicePayload_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateInvoicePayload): _CreateInvoicePayload {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_CreateMaterialPayload_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateMaterialPayload): _CreateMaterialPayload {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_CreatePhasePayload_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePhasePayload): _CreatePhasePayload {
    return to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_CreateSupplierPayload_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateSupplierPayload): _CreateSupplierPayload {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_DeliveryStatus_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryStatus): _DeliveryStatus {
    return to_candid_variant_n94(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceLineItem_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceLineItem): _InvoiceLineItem {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceStatus_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n103(_uploadFile, _downloadFile, value);
}
function to_candid_LogInflowPayload_n112(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogInflowPayload): _LogInflowPayload {
    return to_candid_record_n113(_uploadFile, _downloadFile, value);
}
function to_candid_LogOutflowPayload_n114(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogOutflowPayload): _LogOutflowPayload {
    return to_candid_record_n115(_uploadFile, _downloadFile, value);
}
function to_candid_MaterialCategory_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialCategory): _MaterialCategory {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n107(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n108(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterUserPayload_n116(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterUserPayload): _RegisterUserPayload {
    return to_candid_record_n117(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n118(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n119(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n99(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateBudgetPayload_n120(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateBudgetPayload): _UpdateBudgetPayload {
    return to_candid_record_n121(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateInvoiceStatusPayload_n123(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateInvoiceStatusPayload): _UpdateInvoiceStatusPayload {
    return to_candid_record_n124(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProjectPayload_n125(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProjectPayload): _UpdateProjectPayload {
    return to_candid_record_n126(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus | null): [] | [_InvoiceStatus] {
    return value === null ? candid_none() : candid_some(to_candid_InvoiceStatus_n102(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n106(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus | null): [] | [_ProjectStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ProjectStatus_n107(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n122(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectId | null): [] | [_ProjectId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplierId | null): [] | [_SupplierId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryStatus | null): [] | [_DeliveryStatus] {
    return value === null ? candid_none() : candid_some(to_candid_DeliveryStatus_n93(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialId | null): [] | [_MaterialId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType | null): [] | [_TransactionType] {
    return value === null ? candid_none() : candid_some(to_candid_TransactionType_n98(_uploadFile, _downloadFile, value));
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projectId: ProjectId;
    notes?: string;
    allocatedAmount: number;
    category: BudgetCategory;
}): {
    projectId: _ProjectId;
    notes: [] | [string];
    allocatedAmount: number;
    category: _BudgetCategory;
} {
    return {
        projectId: value.projectId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        allocatedAmount: value.allocatedAmount,
        category: to_candid_BudgetCategory_n11(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n113(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionDate: Timestamp;
    materialId: MaterialId;
    projectId: ProjectId;
    notes?: string;
    quantity: number;
    supplierId?: SupplierId;
    phaseId?: PhaseId;
    unitCost: number;
    qrCode?: string;
}): {
    transactionDate: _Timestamp;
    materialId: _MaterialId;
    projectId: _ProjectId;
    notes: [] | [string];
    quantity: number;
    supplierId: [] | [_SupplierId];
    phaseId: [] | [_PhaseId];
    unitCost: number;
    qrCode: [] | [string];
} {
    return {
        transactionDate: value.transactionDate,
        materialId: value.materialId,
        projectId: value.projectId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        quantity: value.quantity,
        supplierId: value.supplierId ? candid_some(value.supplierId) : candid_none(),
        phaseId: value.phaseId ? candid_some(value.phaseId) : candid_none(),
        unitCost: value.unitCost,
        qrCode: value.qrCode ? candid_some(value.qrCode) : candid_none()
    };
}
function to_candid_record_n115(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionDate: Timestamp;
    materialId: MaterialId;
    projectId: ProjectId;
    notes?: string;
    quantity: number;
    phaseId?: PhaseId;
    unitCost: number;
    qrCode?: string;
}): {
    transactionDate: _Timestamp;
    materialId: _MaterialId;
    projectId: _ProjectId;
    notes: [] | [string];
    quantity: number;
    phaseId: [] | [_PhaseId];
    unitCost: number;
    qrCode: [] | [string];
} {
    return {
        transactionDate: value.transactionDate,
        materialId: value.materialId,
        projectId: value.projectId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        quantity: value.quantity,
        phaseId: value.phaseId ? candid_some(value.phaseId) : candid_none(),
        unitCost: value.unitCost,
        qrCode: value.qrCode ? candid_some(value.qrCode) : candid_none()
    };
}
function to_candid_record_n117(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
    email: string;
}): {
    name: string;
    role: _Role;
    email: string;
} {
    return {
        name: value.name,
        role: to_candid_Role_n118(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_record_n121(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notes?: string;
    allocatedAmount?: number;
}): {
    notes: [] | [string];
    allocatedAmount: [] | [number];
} {
    return {
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        allocatedAmount: value.allocatedAmount ? candid_some(value.allocatedAmount) : candid_none()
    };
}
function to_candid_record_n124(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: InvoiceStatus;
    invoiceId: InvoiceId;
}): {
    status: _InvoiceStatus;
    invoiceId: _InvoiceId;
} {
    return {
        status: to_candid_InvoiceStatus_n102(_uploadFile, _downloadFile, value.status),
        invoiceId: value.invoiceId
    };
}
function to_candid_record_n126(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: ProjectStatus;
    name?: string;
    description?: string;
    siteLocation?: string;
    totalBudget?: number;
}): {
    status: [] | [_ProjectStatus];
    name: [] | [string];
    description: [] | [string];
    siteLocation: [] | [string];
    totalBudget: [] | [number];
} {
    return {
        status: value.status ? candid_some(to_candid_ProjectStatus_n107(_uploadFile, _downloadFile, value.status)) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        siteLocation: value.siteLocation ? candid_some(value.siteLocation) : candid_none(),
        totalBudget: value.totalBudget ? candid_some(value.totalBudget) : candid_none()
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projectId: ProjectId;
    notes?: string;
    expectedDate: Timestamp;
    supplierId: SupplierId;
}): {
    projectId: _ProjectId;
    notes: [] | [string];
    expectedDate: _Timestamp;
    supplierId: _SupplierId;
} {
    return {
        projectId: value.projectId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        expectedDate: value.expectedDate,
        supplierId: value.supplierId
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lineItems: Array<InvoiceLineItem>;
    dueDate?: Timestamp;
    projectId: ProjectId;
    notes?: string;
    supplierId?: SupplierId;
}): {
    lineItems: Array<_InvoiceLineItem>;
    dueDate: [] | [_Timestamp];
    projectId: _ProjectId;
    notes: [] | [string];
    supplierId: [] | [_SupplierId];
} {
    return {
        lineItems: to_candid_vec_n26(_uploadFile, _downloadFile, value.lineItems),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        projectId: value.projectId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        supplierId: value.supplierId ? candid_some(value.supplierId) : candid_none()
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCost: number;
    description: string;
    materialId?: MaterialId;
    quantity: number;
    unitCost: number;
}): {
    totalCost: number;
    description: string;
    materialId: [] | [_MaterialId];
    quantity: number;
    unitCost: number;
} {
    return {
        totalCost: value.totalCost,
        description: value.description,
        materialId: value.materialId ? candid_some(value.materialId) : candid_none(),
        quantity: value.quantity,
        unitCost: value.unitCost
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    unit: string;
    projectId: ProjectId;
    category: MaterialCategory;
    reorderThreshold: number;
}): {
    name: string;
    unit: string;
    projectId: _ProjectId;
    category: _MaterialCategory;
    reorderThreshold: number;
} {
    return {
        name: value.name,
        unit: value.unit,
        projectId: value.projectId,
        category: to_candid_MaterialCategory_n42(_uploadFile, _downloadFile, value.category),
        reorderThreshold: value.reorderThreshold
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: Timestamp;
    name: string;
    description: string;
    budgetAllocation: number;
    projectId: ProjectId;
    startDate?: Timestamp;
}): {
    endDate: [] | [_Timestamp];
    name: string;
    description: string;
    budgetAllocation: number;
    projectId: _ProjectId;
    startDate: [] | [_Timestamp];
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        name: value.name,
        description: value.description,
        budgetAllocation: value.budgetAllocation,
        projectId: value.projectId,
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    materialCategories: Array<MaterialCategory>;
    name: string;
    contactPerson: string;
    email: string;
    address: string;
    phone: string;
}): {
    materialCategories: Array<_MaterialCategory>;
    name: string;
    contactPerson: string;
    email: string;
    address: string;
    phone: string;
} {
    return {
        materialCategories: to_candid_vec_n60(_uploadFile, _downloadFile, value.materialCategories),
        name: value.name,
        contactPerson: value.contactPerson,
        email: value.email,
        address: value.address,
        phone: value.phone
    };
}
function to_candid_variant_n103(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    Paid: null;
} | {
    Draft: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
} {
    return value == InvoiceStatus.Paid ? {
        Paid: null
    } : value == InvoiceStatus.Draft ? {
        Draft: null
    } : value == InvoiceStatus.Cancelled ? {
        Cancelled: null
    } : value == InvoiceStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n108(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    Inactive: null;
} | {
    Active: null;
} | {
    Completed: null;
} {
    return value == ProjectStatus.Inactive ? {
        Inactive: null
    } : value == ProjectStatus.Active ? {
        Active: null
    } : value == ProjectStatus.Completed ? {
        Completed: null
    } : value;
}
function to_candid_variant_n119(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    ProjectManager: null;
} | {
    Admin: null;
} | {
    SiteEngineer: null;
} | {
    FinanceProcurement: null;
} {
    return value == Role.ProjectManager ? {
        ProjectManager: null
    } : value == Role.Admin ? {
        Admin: null
    } : value == Role.SiteEngineer ? {
        SiteEngineer: null
    } : value == Role.FinanceProcurement ? {
        FinanceProcurement: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BudgetCategory): {
    Labor: null;
} | {
    Overhead: null;
} | {
    Materials: null;
} | {
    Other: null;
} | {
    Equipment: null;
} {
    return value == BudgetCategory.Labor ? {
        Labor: null
    } : value == BudgetCategory.Overhead ? {
        Overhead: null
    } : value == BudgetCategory.Materials ? {
        Materials: null
    } : value == BudgetCategory.Other ? {
        Other: null
    } : value == BudgetCategory.Equipment ? {
        Equipment: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialCategory): {
    Steel: null;
} | {
    Plumbing: null;
} | {
    Sand: null;
} | {
    Cement: null;
} | {
    Wood: null;
} | {
    Bricks: null;
} | {
    Aggregate: null;
} | {
    Paint: null;
} | {
    Electrical: null;
} | {
    Other: null;
} {
    return value == MaterialCategory.Steel ? {
        Steel: null
    } : value == MaterialCategory.Plumbing ? {
        Plumbing: null
    } : value == MaterialCategory.Sand ? {
        Sand: null
    } : value == MaterialCategory.Cement ? {
        Cement: null
    } : value == MaterialCategory.Wood ? {
        Wood: null
    } : value == MaterialCategory.Bricks ? {
        Bricks: null
    } : value == MaterialCategory.Aggregate ? {
        Aggregate: null
    } : value == MaterialCategory.Paint ? {
        Paint: null
    } : value == MaterialCategory.Electrical ? {
        Electrical: null
    } : value == MaterialCategory.Other ? {
        Other: null
    } : value;
}
function to_candid_variant_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryStatus): {
    InTransit: null;
} | {
    Delivered: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
} {
    return value == DeliveryStatus.InTransit ? {
        InTransit: null
    } : value == DeliveryStatus.Delivered ? {
        Delivered: null
    } : value == DeliveryStatus.Cancelled ? {
        Cancelled: null
    } : value == DeliveryStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    Outflow: null;
} | {
    Inflow: null;
} {
    return value == TransactionType.Outflow ? {
        Outflow: null
    } : value == TransactionType.Inflow ? {
        Inflow: null
    } : value;
}
function to_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InvoiceLineItem>): Array<_InvoiceLineItem> {
    return value.map((x)=>to_candid_InvoiceLineItem_n27(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MaterialCategory>): Array<_MaterialCategory> {
    return value.map((x)=>to_candid_MaterialCategory_n42(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
